### ISSUE TITLE
After install can't run , module not found.

### ISSUE THREAD

**Issue by M0348** [erdieee/allusion#2]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/Alt/allusion/allusion/__main__.py", line 1, in <module>
    from allusion.main import main
ModuleNotFoundError: No module named 'allusion'

**Comment by erdieee** [comment]
My bad for closing the issue. Please pull the latest version and let me know if it works now. Make sure to follow the updated installation guide :)

**Comment by M0348** [comment]
Works now thanks for the update.
